INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Test', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('NOW', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('MATHEUS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('QUEREM', NOW());

INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Test', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('NOW', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('MATHEUS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('QUEREM', NOW());

INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Test', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('NOW', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('MATHEUS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('QUEREM', NOW());

INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Test', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('NOW', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('MATHEUS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('QUEREM', NOW());

INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Test', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('NOW', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('MATHEUS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('QUEREM', NOW());

INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Test', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('NOW', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('MATHEUS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('QUEREM', NOW());

INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Test', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('NOW', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('MATHEUS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('QUEREM', NOW());

INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Test', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('NOW', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('MATHEUS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('QUEREM', NOW());

INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Test', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('NOW', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('MATHEUS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('QUEREM', NOW());

INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Car', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Test', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('NOW', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('MATHEUS', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('QUEREM', NOW());